### ISSUE TITLE
Export types for external usage

### ISSUE THREAD

**Issue by xinbenlv** [dcoffey-zengenti/node-rdap#5]
Hi @dcoffey-zengenti thanks for building this project. This is the best client library I found to query  RDAP. 

Have you considered export types so caller can also use it?

**Comment by dcoffey-zengenti** [comment]
@xinbenlv Thank you for your feedback, I have re-exported the types from the entry file in v0.4.2! You can now import the types as follows:

```typescript
import type { RdapAutnumResponse, RdapDomainResponse, RdapIpResponse } from 'node-rdap';
```
